export default Object.freeze({
  GET_ALL_REQUEST: 'RECIPES_GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'RECIPES_GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'RECIPES_GET_ALL_FAILURE',

  GET_SINGLE_REQUEST: 'RECIPES_GET_SINGLE_REQUEST',
  GET_SINGLE_SUCCESS: 'RECIPES_GET_SINGLE_SUCCESS',
  GET_SINGLE_FAILURE: 'RECIPES_GET_SINGLE_FAILURE',

  GET_MY_ALL_REQUEST: 'RECIPES_GET_MY_ALL_REQUEST',
  GET_MY_ALL_SUCCESS: 'RECIPES_GET_MY_ALL_SUCCESS',
  GET_MY_ALL_FAILURE: 'RECIPES_GET_MY_ALL_FAILURE',

  GET_MY_SINGLE_REQUEST: 'RECIPES_GET_MY_SINGLE_REQUEST',
  GET_MY_SINGLE_SUCCESS: 'RECIPES_GET_MY_SINGLE_SUCCESS',
  GET_MY_SINGLE_FAILURE: 'RECIPES_GET_MY_SINGLE_FAILURE',

  CREATE_REQUEST: 'RECIPES_CREATE_REQUEST',
  CREATE_SUCCESS: 'RECIPES_CREATE_SUCCESS',
  CREATE_FAILURE: 'RECIPES_CREATE_FAILURE',

  UPDATE_SINGLE_REQUEST: 'RECIPES_UPDATE_SINGLE_REQUEST',
  UPDATE_SINGLE_SUCCESS: 'RECIPES_UPDATE_SINGLE_SUCCESS',
  UPDATE_SINGLE_FAILURE: 'RECIPES_UPDATE_SINGLE_FAILURE',

  DELETE_SINGLE_REQUEST: 'RECIPES_DELETE_SINGLE_REQUEST',
  DELETE_SINGLE_SUCCESS: 'RECIPES_DELETE_SINGLE_SUCCESS',
  DELETE_SINGLE_FAILURE: 'RECIPES_DELETE_SINGLE_FAILURE'
});
