export default Object.freeze({
  GET_INFO_REQUEST: 'USER_GET_INFO_REQUEST',
  GET_INFO_SUCCESS: 'USER_GET_INFO_SUCCESS',
  GET_INFO_FAILURE: 'USER_GET_INFO_FAILURE',

  MY_GET_INFO_REQUEST: 'MY_USER_GET_INFO_REQUEST',
  MY_GET_INFO_SUCCESS: 'MY_USER_GET_INFO_SUCCESS',
  MY_GET_INFO_FAILURE: 'MY_USER_GET_INFO_FAILURE',

  PUT_INFO_REQUEST: 'USER_PUT_INFO_REQUEST',
  PUT_INFO_SUCCESS: 'USER_PUT_INFO_SUCCESS',
  PUT_INFO_FAILURE: 'USER_PUT_INFO_FAILURE',

  DELETE_USER_REQUEST: 'USER_DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'USER_DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'USER_DELETE_USER_FAILURE'
});
