export default Object.freeze({
  SIGN_IN_REQUEST: 'AUTH_SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'AUTH_SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'AUTH_SIGN_IN_FAILURE',

  SIGN_UP_REQUEST: 'AUTH_SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'AUTH_SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'AUTH_SIGN_UP_FAILURE',

  SIGN_OUT_REQUEST: 'AUTH_SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'AUTH_SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'AUTH_SIGN_OUT_FAILURE',

  CLEAR_REDUCER: 'AUTH_CLEAR_REDUCER'
});
